lastupdatecheck: 0
recentrepos:
    - /Users/orp/dev/playbook-orchestrator
    - /Users/orp/dev/steps
    - /Users/orp/dev/common
    - /Users/orp/dev/k8s-manifests
    - /Users/orp/dev/spd
    - /Users/orp/dev/steps-sdk-go
    - /Users/orp/dev/files
    - /Users/orp/dev/iac
    - /Users/orp/dev/app
    - /Users/orp/dev/mgmt
    - /Users/orp/dev/github-workflows
startuppopupversion: 5
didshowhunkstaginghint: true
lastversion: 0.55.1
customcommandshistory: []
hidecommandlog: false
